version: "2"
services:
    web:
        build: ./app
        ports:
            - "3000:3000"
        links:
            - mongo
        volumes:
            - ./app:/usr/src/app
    mongo:
        image: mongo
        volumes:
            - ./data:/data/db
        ports:
            - "27017:27017"
